title: Sam J Griffin
base_url: https://www.samjgriffin.com
email: samjgriffin89@gmail.com

meta_title: Sam J Griffin | Payments & POS Specialist
description: I enjoy solving complex problems like scalability of applications and working with payment and point of sale cloud api integrations.

google_analytics_id: G-1MRVVZX7R8
google_site_verification: cT3CHL7PrHfUex3GIuLkyjnk-deuZyedUYGqJGOKGEc

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - .gitignore
  - README.md
